#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    line1,          sensorLineFollower)
#pragma config(Sensor, in2,    line2,          sensorLineFollower)
#pragma config(Sensor, in3,    degree1,        sensorPotentiometer)
#pragma config(Sensor, dgtl1,  sonarSensor,    sensorSONAR_cm)
#pragma config(Sensor, dgtl3,  leftHand,       sensorTouch)
#pragma config(Sensor, dgtl4,  rightHand,      sensorTouch)
#pragma config(Sensor, dgtl8,  backTouch,      sensorTouch)
#pragma config(Sensor, I2C_1,  L,              sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  R,              sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           left,          tmotorVex393_HBridge, openLoop, reversed, driveLeft, encoderPort, I2C_1)
#pragma config(Motor,  port4,           hand1,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           hand2,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           arm1,          tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           arm2,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          right,         tmotorVex393_HBridge, openLoop, driveRight, encoderPort, I2C_2)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(0)
#pragma userControlDuration(60)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

/////////////////////////////////////////////////////////////////////////////////////////
//
//                         Driver Skills Template
//
// This is a template for the driver skills competition. It is identical in structure to
// the standard competition template except that the two "#pragma' statements above (and
// copied below) adjust the time limits for the competition.
//				#pragma autonomousDuration(0)
//				#pragma userControlDuration(60)
// The autonomous duration for "Driver Skills" is zero; i.e. there is no autonomous phase.
// The user control duration is 60 seconds
//
// NOTE: The above two pragmas only impact the Crystal implementation. For systems using
//       VEXNET, the VEXNET system ignores these statements as it has the durations
//       for the competition built-in.
//
// Whenever this user program is run, the duration is automatically sent to the VEX master
// processor. The master CPU will only accept these commands once per power=on cycle. So, it's
// best to power cycle your VEX to ensure that they get recognized in case you were
// previously running a standard competition program with different durations.
//
// Testing Via Crystals:
// ====================
//
// The procedure to test a Driver Skills program using the crystals is as follows:
//
// 1. Turn off power to the Crystal transmitter/joysticks.
//
// 2. Turn on your VEX so that the Driver Skills program is running.
//
// 3. Driver skills program segment of your program will start running. At the end of 60
//    seconds the VEX Master CPU will turn off the motors.

// 4. Repeat the above sequence
//
//
// Testing Via VEXNET Using VEXNET Competition Switch
// ==================================================
//
// The procedure to test a Driver Skills program using VEXNET Competition Switch is as follows:
//
// 1. Set the two switches on the Competition switch to "DISABLE" and "USER CONTROL"
//
// 2. Start the Driver skills program
//
// 3. Set Switch to ENABLE from DISABLE
//
// 4. You need to manually time the 60 second duration.
//
// 5. Set Switch to DISABLE
//
// 6. Repeat from step (3) to run subsequent test runs. There's no need to reset the VEX or
//    restart your user program.
//
//
// Testing Via VEXNET Using ROBOTC IDE
// ==================================================
//
// It is not necessary to own a VEXNET switch. ROBOTC has a test window that allows the same functionality.
// The test window has three buttons for "DISABLE", "AUTONOMOUS", "USER CONTROL".
//
// 1. Open the ROBOTC Debugger. Then open the "Competition Control" Debugger window.
//
// 2. Start your Driver Skills program running.
//
// 3. Click the "DISABLED" button on the "Competition Control" window.
//
// 4. Click the "USER CONTROL" button on the "Competition Control" window.
//
// 5. You need to manually time the 60 second duration.
//
// 6. Click the "DISABLED" button on the "Competition Control" window.
//
// 7. Repeat from step (4) to run subsequent test runs. There's no need to reset the VEX or
//    restart your user program.
//
/////////////////////////////////////////////////////////////////////////////////////////

/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////
int a[]={1,1,1,1};
float markDistanceM=20;
int armPlace;
int lineVule=985;
bool passLine;
void move(int Speed,int times);
void init();
void turn(int Speed,int times);
void riseArm(int Speed,int riseDegree);
void openClam();
void closeClam();
int findLine();
bool distentFind(float markDistance);
void lineFollow(int speed);
void startAction();
void getStar();
void initAll();

int shortTurn=133;
int shortTurnSpeed=-127;
int longTurn=400;
int longTurnSpeed=127;

int armPlace1=2340;
int armPlace2=2680;
int armPlace3=4095;

void pre_auton()
{
	startAction();
  bStopTasksBetweenModes = true;
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// The "Driver Skills" competition has no autonomous phase. Simply leave the following
// placeholder.
//
/////////////////////////////////////////////////////////////////////////////////////////

task autonomous()
{
	/*********************************/
		bool findLineM=false;
		while(!passLine){
			if(findLine()==0){
				move(60,shortTurn);
				if(findLineM)passLine=true;
			}
			else if(findLine()==1){
				turn(shortTurnSpeed,shortTurn);
			}
			else if(findLine()==2){
				turn(-shortTurnSpeed,shortTurn);
			}
			else if(findLine()==3){
				turn(longTurnSpeed,longTurn);
				findLineM=true;
			}
		}
		/*********************************/
		openClam();
		while(true){
			move(127,10);
			if(distentFind(markDistanceM)){
				closeClam();
				riseArm(60,armPlace2);
				turn(longTurnSpeed,longTurn);
				move(-60,100);
				riseArm(60,armPlace3);
				openClam();
				riseArm(60,armPlace1);
				move(60,100);
				turn(-longTurnSpeed,longTurn);
				riseArm(60,armPlace1);
				break;
			}
		}
		/*********************************/
		while(true){
			lineFollow(100);
			if(SensorValue(backTouch)==0)break;
		}
		for(int i=0;i<4;i++){//need to change
			move(127,a[i]);
			getStar();
		}
		turn(longTurnSpeed,longTurn);
		while(true){
			move(100,10);
			if(SensorValue(backTouch)==0)break;
		}
		closeClam();
		for(int i=0;i<10;i++){
			riseArm(127,armPlace3);
			delay(100);
			riseArm(127,armPlace1);
			turn(longTurnSpeed,longTurn);
			move(100,10);
			turn(-longTurnSpeed,longTurn);
		}

	//AutonomousCodePlaceholderForTesting();  // Remove this function call once you have "real" code.
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task usercontrol()
{
	// User control code here, inside the loop

	while (true)
	{
	  // This is the main execution loop for the user control program. Each time through the loop
	  // your program should update motor + servo values based on feedback from the joysticks.

	  // .....................................................................................
	  // Insert user code here. This is where you use the joystick values to update your motors, etc.
	  // .....................................................................................

		if(vexRT[Btn6D]==0)closeClam();
		else if(vexRT[Btn6U]==0)openClam();
		else if(vexRT[Btn5U]==0)riseArm(63,3000);
		else if(vexRT[Btn5D]==0)riseArm(63,1000);
	  //UserControlCodePlaceholderForTesting(); // Remove this function call once you have "real" code.
	  motor[right] = vexRT[Ch1];							// Remove these as well and replace with your appropriate code
	  motor[left] = vexRT[Ch4];							// Remove these as well and replace with your appropriate code
	}
}


void startAction(){
	initAll();
	riseArm(60,armPlace2);
	closeClam();
	openClam();
	riseArm(60,armPlace1);

}
void init(){
	resetMotorEncoder(right);
  resetMotorEncoder(left);
}
void initAll(){
		resetMotorEncoder(right);
    resetMotorEncoder(left);
    passLine=false;
    armPlace=SensorValue(degree1);
}

void lineFollow(int speed){
	if(findLine()==0){
		move(speed,10);
	}
	else if(findLine()==1){
		turn(shortTurnSpeed,shortTurn);
	}
	else if(findLine()==2){
		turn(-shortTurnSpeed,shortTurn);
	}
	else if(findLine()==3){
		turn(longTurnSpeed,longTurn);
	}

}

void getStar(){
	turn(longTurnSpeed,longTurn);
	openClam();
	move(60,100);
	closeClam();
	riseArm(60,armPlace2);
	move(-60,200);
	riseArm(60,armPlace3);
	openClam();
	riseArm(60,armPlace1);
	move(60,100);
	turn(-longTurnSpeed,longTurn);
}

void move(int Speed,int times){
	int counter=0;
	int rightCounter;
	int leftCounter;
	while(counter< times)
  {
		motor[left]=Speed;
		motor[right]=Speed;
		rightCounter=getMotorEncoder(right);
		leftCounter=getMotorEncoder(left);
		counter=(rightCounter+leftCounter)/2;
	}
		motor[left]=0;
		motor[right]=0;
		delay(10);
		init();
}

void turn(int Speed,int times){
	int counter=0;
	while(counter< times)
  {
		motor[left]=-Speed;
		motor[right]=Speed;
		int rightCounter=getMotorEncoder(right);
		int leftCounter=getMotorEncoder(left);
		if(Speed>0)counter=getMotorEncoder(right);
		else counter=getMotorEncoder(left);
	}
		motor[left]=0;
		motor[right]=0;
		delay(10);
		init();
}

void closeClam(){
		motor[hand1]=-127;
		motor[hand2]=-127;
}

void openClam(){
	while(SensorValue(leftHand) == 1&&SensorValue(rightHand) == 1){
		motor[hand1]=127;
		motor[hand2]=127;
		delay(5000);
	}
		motor[hand1]=0;
		motor[hand2]=0;
}

void riseArm(int Speed,int riseDegree){
	if(armPlace>riseDegree){
		while(armPlace> riseDegree)
 	 	{
	  	motor[arm1]=-Speed;
			motor[arm2]=-Speed;
			armPlace=SensorValue(degree1);
		}
	}
	else{
		while(armPlace<= riseDegree)
 	 	{
	  	motor[arm1]=Speed;
			motor[arm2]=Speed;
			armPlace=SensorValue(degree1);
		}
	}
	 	motor[arm1]=0;
		motor[arm2]=0;
		delay(10);
}
int findLine(){
	int valueL=SensorValue(line1);
	int valueR=SensorValue(line2);
	//lineVule=valueR;
	if(valueL>=lineVule&&valueR>=lineVule){
		return 0;
	}else if(valueL>=lineVule&&valueR<lineVule){//Right have white
		return 1;
	}
	else if(valueR>=lineVule&&valueL<lineVule){//Left have white
		return 2;
	}
	else if(valueR<lineVule&&valueL<lineVule){
		return 3;
	}
	return -1;
}

bool distentFind(float markDistance){
	if(markDistance>SensorValue(sonarSensor)){
		return true;
	}
	return false;
}
